# Generated by Django 5.0.1 on 2024-01-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_staff_notification_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff_notification",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="staff_notification",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="staff_notification",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="staff_notification",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/notification_profile_pic"
            ),
        ),
    ]
