# Generated by Django 5.0.1 on 2024-01-25 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_staff_notification_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff_notification",
            name="created_at",
        ),
    ]
