# Generated by Django 5.0.1 on 2024-03-17 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_staff_notification_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance_report",
            name="id",
        ),
        migrations.RemoveField(
            model_name="attendance_report",
            name="staff_id",
        ),
        migrations.RemoveField(
            model_name="attendance_report",
            name="task_id",
        ),
        migrations.AddField(
            model_name="attendance_report",
            name="name_report",
            field=models.TextField(default=4),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="attendance_report",
            name="attendance_id",
        ),
        migrations.AddField(
            model_name="attendance_report",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance_report",
            name="new_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.staff",
            ),
        ),
        migrations.AlterField(
            model_name="attendance_report",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
