# Generated by Django 5.0.1 on 2024-03-17 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_remove_attendance_report_id_and_more_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance_report",
            name="new_id",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.staff",
            ),
        ),
    ]
