# Generated by Django 5.0.1 on 2024-03-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance_report",
            name="description",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="attendance_report",
            name="name_report",
            field=models.CharField(max_length=200),
        ),
    ]
