# Generated by Django 5.0.1 on 2024-03-17 15:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_remove_attendance_report_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance_report",
            name="attendance_id",
        ),
        migrations.AddField(
            model_name="attendance_report",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=datetime.date,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance_report",
            name="staff_id",
            field=models.ForeignKey(
                default=datetime.date,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.staff",
            ),
            preserve_default=False,
        ),
    ]
