# Generated by Django 5.0.1 on 2024-03-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_attendance_report_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance_report",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
