# Generated by Django 5.0.1 on 2024-03-27 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_attendance_report_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance_report",
            name="staff_id",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
