# Generated by Django 5.0.1 on 2024-03-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_remove_attendance_report_attendance_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attendance_Report",
        ),
    ]
