# Generated by Django 5.0.1 on 2024-03-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_attendance_report_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance_report",
            name="attendance_id",
        ),
    ]
