# Generated by Django 5.0.1 on 2024-03-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_remove_attendance_report_attendance_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance_report",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
