# Generated by Django 5.0.1 on 2024-04-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_deal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("OWNER_ID", models.CharField()),
                ("DESCRIPTION", models.TextField()),
                ("CREATED", models.DateTimeField()),
                ("LAST_UPDATED", models.DateTimeField()),
                ("COMPLETED", models.TextField()),
                ("START_TIME", models.DateTimeField()),
                ("END_TIME", models.DateTimeField()),
                ("DEADLINE", models.DateTimeField()),
            ],
        ),
    ]
