# Generated by Django 5.0.1 on 2024-04-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bitrix_staff_id",
            field=models.CharField(null=True),
        ),
    ]
