# Generated by Django 5.0.1 on 2024-03-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_alter_attendance_report_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance_report",
            old_name="id",
            new_name="attendance_id",
        ),
    ]
