# Generated by Django 5.0.1 on 2024-03-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_rename_id_attendance_report_attendance_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attendance_Report",
        ),
        migrations.CreateModel(
            name="Attendance_Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_report", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
