# Generated by Django 5.0.1 on 2024-04-03 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_remove_deal_staff_id_deal_bitrix_staff_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="bitrix_staff_id",
            field=models.ForeignKey(
                db_column="bitrix_staff_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
