# Generated by Django 5.0.1 on 2024-03-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_delete_attendance_report_attendance_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance_report",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
