# Generated by Django 5.0.1 on 2024-04-03 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_alter_customuser_bitrix_staff_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="OWNER_ID",
        ),
        migrations.AddField(
            model_name="case",
            name="bitrix_staff_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="bitrix_staff_id",
                unique=True,
            ),
        ),
    ]
