# Generated by Django 5.0.1 on 2024-03-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
