# Generated by Django 5.0.1 on 2024-04-03 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_remove_case_owner_id_case_bitrix_staff_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="bitrix_staff_id",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="bitrix_staff_id",
            ),
        ),
    ]
