# Generated by Django 5.0.1 on 2024-03-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_customer_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance_report",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
