# Generated by Django 5.0.1 on 2024-03-17 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_alter_attendance_report_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance_report",
            name="staff_id",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="app.staff"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendance_report",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
