# Generated by Django 5.0.1 on 2024-03-17 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_attendance_report_staff_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance_report",
            name="staff_id",
        ),
    ]
