# Generated by Django 5.0.1 on 2024-04-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_bitrix24"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitrix24",
            name="name",
            field=models.TextField(default="webhook"),
        ),
    ]
