# Generated by Django 5.0.1 on 2024-04-04 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_bitrix24_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bitrix24",
            name="name",
        ),
    ]
