# Generated by Django 5.0.1 on 2024-03-17 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_remove_attendance_report_staff_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance_report",
            name="staff_id",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="app.staff"
            ),
            preserve_default=False,
        ),
    ]
