# Generated by Django 5.0.1 on 2024-04-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_remove_bitrix24_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitrix24",
            name="name_webhook",
            field=models.TextField(default="one"),
        ),
    ]
