# Generated by Django 5.0.1 on 2024-03-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_delete_attendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance_report",
            name="id",
        ),
        migrations.AlterField(
            model_name="attendance_report",
            name="staff_id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
