# Generated by Django 5.0.1 on 2024-04-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_alter_case_bitrix_staff_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="END_TIME",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="START_TIME",
            field=models.DateTimeField(null=True),
        ),
    ]
