# Generated by Django 5.0.1 on 2024-03-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_remove_attendance_report_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff_notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff_notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
