# Generated by Django 5.0.1 on 2024-03-17 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_staff_notification_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff_notification",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="staff_notification",
            name="updated_at",
        ),
    ]
