# Generated by Django 5.0.1 on 2024-03-17 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_remove_staff_notification_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff_notification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2024, 3, 18, 1, 40, 58, 292303),
            ),
            preserve_default=False,
        ),
    ]
