# Generated by Django 5.0.1 on 2024-04-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_taskcontrol"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcontrol",
            name="TIME_ESTIMATE",
            field=models.TextField(default=0, null=True),
        ),
    ]
