# Generated by Django 5.0.1 on 2024-04-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_callcontrol"),
    ]

    operations = [
        migrations.AddField(
            model_name="callcontrol",
            name="COST",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="callcontrol",
            name="VOTE",
            field=models.TextField(null=True),
        ),
    ]
