# Generated by Django 5.0.1 on 2024-04-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_callcontrol_cost_callcontrol_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="callcontrol",
            name="DateCreate",
            field=models.DateTimeField(null=True),
        ),
    ]
