# Generated by Django 5.0.1 on 2024-04-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_callcontrol_datecreate"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcontrol",
            name="CREATED_DATE",
            field=models.DateTimeField(null=True),
        ),
    ]
