# Generated by Django 5.0.1 on 2024-04-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_alter_attendance_report_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance_report",
            name="Errors",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="attendance_report",
            name="general_comment",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="attendance_report",
            name="performance",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="attendance_report",
            name="possible_risks",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="attendance_report",
            name="practices_improving_your",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="attendance_report",
            name="progress",
            field=models.TextField(null=True),
        ),
    ]
