# Generated by Django 5.0.1 on 2024-04-23 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_alter_staff_address_alter_staff_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="admin",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
