# Generated by Django 5.0.1 on 2024-04-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_alter_staff_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcontrol",
            name="CREATED_a",
            field=models.DateTimeField(null=True),
        ),
    ]
