# Generated by Django 5.0.1 on 2024-04-23 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_remove_taskcontrol_created_a_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="admin",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="bitrix_staff_id",
            ),
        ),
    ]
