# Generated by Django 5.0.1 on 2024-04-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0053_alter_staff_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="WORK_DEPARTMENT",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="WORK_POSITION",
            field=models.TextField(null=True),
        ),
    ]
