# Generated by Django 5.0.1 on 2024-04-23 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_customuser_work_department_customuser_work_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcontrol",
            name="bitrix_staff_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="bitrix_staff_id",
            ),
        ),
    ]
