# Generated by Django 5.0.1 on 2024-04-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_alter_taskcontrol_bitrix_staff_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcontrol",
            name="CREATED_BY",
            field=models.CharField(null=True),
        ),
    ]
