# Generated by Django 5.0.1 on 2024-04-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_taskcontrol_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskcontrol",
            old_name="CREATED_BY",
            new_name="GROUP_PROJECTS",
        ),
    ]
