# Generated by Django 5.0.1 on 2024-04-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_rename_created_by_taskcontrol_group_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="media/profile_pic"),
        ),
    ]
