# Generated by Django 5.0.1 on 2024-04-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0058_alter_customuser_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcontrol",
            name="DEADLINE",
            field=models.DateTimeField(null=True),
        ),
    ]
