# Generated by Django 5.0.1 on 2024-04-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0059_alter_taskcontrol_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcontrol",
            name="DESCRIPTION",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="taskcontrol",
            name="PRIORITY",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="taskcontrol",
            name="STATUS",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="taskcontrol",
            name="SUBSTATUS",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="taskcontrol",
            name="TITLE",
            field=models.TextField(null=True),
        ),
    ]
