# Generated by Django 5.0.1 on 2024-05-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0060_alter_taskcontrol_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance_report",
            old_name="Errors",
            new_name="errors",
        ),
        migrations.AddField(
            model_name="callcontrol",
            name="COMMENT",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="taskcontrol",
            name="COMMENT",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="taskcontrol",
            name="TASKOFCALL",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[(1, "HOD"), (2, "STAFF")], default=1, max_length=50
            ),
        ),
    ]
