# Generated by Django 5.0.1 on 2024-05-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_rename_errors_attendance_report_errors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcontrol",
            name="COMMENT",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="taskcontrol",
            name="CREATED_DATE",
            field=models.DateTimeField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="taskcontrol",
            name="DEADLINE",
            field=models.DateTimeField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="taskcontrol",
            name="DESCRIPTION",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="taskcontrol",
            name="GROUP_PROJECTS",
            field=models.CharField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="taskcontrol",
            name="PRIORITY",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="taskcontrol",
            name="STATUS",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="taskcontrol",
            name="SUBSTATUS",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="taskcontrol",
            name="TASKOFCALL",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="taskcontrol",
            name="TITLE",
            field=models.TextField(default="", null=True),
        ),
    ]
