# Generated by Django 5.0.1 on 2024-05-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0064_alter_taskcontrol_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="callcontrol",
            name="ID_CALL",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="taskcontrol",
            name="ID_TASK",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="timecontrol",
            name="ID_TIME",
            field=models.CharField(null=True),
        ),
    ]
